//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slowa.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slowa.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Jeszcze raz [T/N].
        /// </summary>
        internal static string sAGAIN {
            get {
                return ResourceManager.GetString("sAGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozwolić na duplikaty znaków [T/N]?.
        /// </summary>
        internal static string sALLOW_DUPLICATES {
            get {
                return ResourceManager.GetString("sALLOW_DUPLICATES", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tworzę słownik.
        /// </summary>
        internal static string sCREATING_DICTIONARY {
            get {
                return ResourceManager.GetString("sCREATING_DICTIONARY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu brak.
        /// </summary>
        internal static string sEMPTY {
            get {
                return ResourceManager.GetString("sEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bląd ładowania słownika. Wyjątek {0}..
        /// </summary>
        internal static string sERR_DIC_LOAD {
            get {
                return ResourceManager.GetString("sERR_DIC_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maksymalna ilość znaków nie może być mniejsza niż minimalna..
        /// </summary>
        internal static string sERR_MAX_NUMBER_TO_SMALL {
            get {
                return ResourceManager.GetString("sERR_MAX_NUMBER_TO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu To musi być liczba..
        /// </summary>
        internal static string sERR_NEED_NUMBER {
            get {
                return ResourceManager.GetString("sERR_NEED_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono pliku słownika {0}..
        /// </summary>
        internal static string sERR_NO_DICTIONARY_FILE_FOUND {
            get {
                return ResourceManager.GetString("sERR_NO_DICTIONARY_FILE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wpisz ciąg znaków bez cyfr. {0} zawiera cyfry..
        /// </summary>
        internal static string sERR_NO_NUMBERS_ALLOWED {
            get {
                return ResourceManager.GetString("sERR_NO_NUMBERS_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie może być większa niż liczba liter.
        /// </summary>
        internal static string sERR_TO_BIG_NUMBER {
            get {
                return ResourceManager.GetString("sERR_TO_BIG_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Za mało znaków {0}. Minimum to {1}..
        /// </summary>
        internal static string sERROR_MORE_LETTERS {
            get {
                return ResourceManager.GetString("sERROR_MORE_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu litera.
        /// </summary>
        internal static string sLETTER1 {
            get {
                return ResourceManager.GetString("sLETTER1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu litery.
        /// </summary>
        internal static string sLETTER2 {
            get {
                return ResourceManager.GetString("sLETTER2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu liter.
        /// </summary>
        internal static string sLETTER3 {
            get {
                return ResourceManager.GetString("sLETTER3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu a [do].
        /// </summary>
        internal static string sMAX_LENGHT {
            get {
                return ResourceManager.GetString("sMAX_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ilość znaków między [od].
        /// </summary>
        internal static string sMIN_LENGHT {
            get {
                return ResourceManager.GetString("sMIN_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu NIE.
        /// </summary>
        internal static string sNO {
            get {
                return ResourceManager.GetString("sNO", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dowolny klawisz by zacząć od nowa..
        /// </summary>
        internal static string sPRESSKEY {
            get {
                return ResourceManager.GetString("sPRESSKEY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj wzór wyszukiwania.
        /// </summary>
        internal static string sSEARCH_PATTERN {
            get {
                return ResourceManager.GetString("sSEARCH_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podpowiedź: wpisz symbol * jako nieznana litera (np. Kw**t).
        /// </summary>
        internal static string sSEARCH_TIP {
            get {
                return ResourceManager.GetString("sSEARCH_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Chcesz podać wzór wyszukiwania?.
        /// </summary>
        internal static string sUSE_SEARCH_PATTERN {
            get {
                return ResourceManager.GetString("sUSE_SEARCH_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Z jakich liter? .
        /// </summary>
        internal static string sWHAT_LETTERS {
            get {
                return ResourceManager.GetString("sWHAT_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Znaleziono {0} słów..
        /// </summary>
        internal static string sWORDS_FOUND {
            get {
                return ResourceManager.GetString("sWORDS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu słów w słowniku.
        /// </summary>
        internal static string sWORDS_IN_DICTIONARY {
            get {
                return ResourceManager.GetString("sWORDS_IN_DICTIONARY", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu TAK.
        /// </summary>
        internal static string sYES {
            get {
                return ResourceManager.GetString("sYES", resourceCulture);
            }
        }
    }
}
